# Generated by Django 6.0.4 on 2026-04-15 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_wallet', models.TextField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.TextField(blank=True, null=True)),
                ('asa_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('total_supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('available_supply', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('legal_documents', models.TextField(blank=True, null=True)),
                ('metadata_json', models.TextField(blank=True, null=True)),
                ('listing_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('sold_out', 'Sold Out'), ('delisted', 'Delisted')], default='inactive', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listed_at', models.DateTimeField(blank=True, null=True)),
                ('delisted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('listing_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='sell', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='authentication_app.asset')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Listing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('group_transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_txn_id', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_transfer_txn_id', models.CharField(blank=True, max_length=255, null=True)),
                ('asa_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('buyer_opt_in_validated', models.BooleanField(default=False)),
                ('buyer_balance_validated', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='authentication_app.asset')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='authentication_app.listing')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('opt_in_status', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='authentication_app.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WalletHolding',
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['owner', '-created_at'], name='Asset_owner_i_9932c2_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['listing_status', '-created_at'], name='Asset_listing_9f34a3_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asa_id'], name='Asset_asa_id_990753_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['asset', 'is_active', '-created_at'], name='Listing_asset_i_b0e279_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer', '-created_at'], name='Transaction_buyer_i_9c2a51_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller', '-created_at'], name='Transaction_seller__691ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['asset', '-created_at'], name='Transaction_asset_i_6e80c7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='Transaction_status_2ce0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tx_id'], name='Transaction_tx_id_f9c81b_idx'),
        ),
        migrations.AddIndex(
            model_name='walletholding',
            index=models.Index(fields=['user', 'asset'], name='WalletHoldi_user_id_882ce7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='walletholding',
            unique_together={('user', 'asset')},
        ),
    ]
