# Generated by Django 6.0.4 on 2026-04-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_user_wallet_address_alter_user_password_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='documents_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='passport_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
