# Generated by Django 6.0.4 on 2026-04-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='discussion__proposa_1f2104_idx',
            old_name='discussion_comment_proposal_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='discussion__recipie_f11f0a_idx',
            old_name='discussion_notification_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='discussion__company_85a60d_idx',
            old_name='discussion_proposal_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='discussion__propose_3aba40_idx',
            old_name='discussion_proposal_proposer_idx',
        ),
        migrations.RenameIndex(
            model_name='proposal',
            new_name='discussion__voting__1ecc71_idx',
            old_name='discussion_proposal_voting_end_idx',
        ),
        migrations.RenameIndex(
            model_name='voterecord',
            new_name='discussion__proposa_67257c_idx',
            old_name='discussion_vote_proposal_voter_idx',
        ),
        migrations.RenameIndex(
            model_name='voterecord',
            new_name='discussion__tx_hash_72dacf_idx',
            old_name='discussion_vote_tx_hash_idx',
        ),
    ]
